error ci-cd
fixed

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -16,7 +16,7 @@ jobs:
     services:
       sql_server_container:
         image: mcr.microsoft.com/mssql/server
-        options: --health-cmd="nc -z localhost 1433" --health-start-period=30s
+        options: --health-cmd="bash -c 'nc -z localhost 1433 && echo ready || exit 1'" --health-start-period=30s
         ports:
           - 1433:1433
         env:
@@ -33,7 +33,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # Set up Docker
+      # Set up Docker Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
@@ -49,6 +49,11 @@ jobs:
         run: |
           docker-compose -f docker-compose.yml build
           docker-compose -f docker-compose.yml up -d
+
+      # Show logs for all containers (in case of failure)
+      - name: Show Docker logs
+        run: |
+          docker-compose -f docker-compose.yml logs
 
       # Wait for SQL Server to be ready
       - name: Wait for SQL Server to be ready
@@ -70,7 +75,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # Set up Docker
+      # Set up Docker Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
